spring:
  elasticsearch:
    rest:
      uris: ${ossp.elasticsearch.uris}
      username: ${ossp.elasticsearch.username}
      password: ${ossp.elasticsearch.password}

ossp:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: cn.aixuxi.ossp.search.server.search.controller